import { createHash } from 'node:crypto';

// Template changes invalidate artifact approval, not source selection or saved prose.
import { RENDERER_VERSION, ARTIFACT_REVIEW_VERSION } from './review-versions';
export { RENDERER_VERSION, ARTIFACT_REVIEW_VERSION } from './review-versions';

function stable(value: any): any {
  if (value instanceof Date) return value.toISOString();
  if (Array.isArray(value)) return value.map(stable);
  if (value && typeof value === 'object') return Object.fromEntries(Object.keys(value).sort().map(k => [k, stable(value[k])]));
  return value;
}
/** Bind approval to all editorial inputs, excluding the approval and generated bytes themselves. */
export function deliveryInputHash(submission: any, data: any = submission.chambersData || {}) {
  const {approved_artifact, previous_approved_artifact, release_verdict, cloned_docx_b64, review_checkpoint, ...inputs} = data;
  return createHash('sha256').update(JSON.stringify(stable({rendererVersion:RENDERER_VERSION,artifactReviewVersion:ARTIFACT_REVIEW_VERSION,practiceArea:submission.practiceArea, targetDirectory:submission.targetDirectory, guideRegion:submission.guideRegion, currentBand:submission.currentBand, inputs}))).digest('hex');
}
export function artifactHash(buffer: Buffer) { return createHash('sha256').update(buffer).digest('hex'); }

/** Preserve only bytes that were approved against the exact pre-edit inputs. */
export function previousApprovedArtifact(submission:any,data:any) {
  const pair=data.approved_artifact;
  if(data.release_verdict?.passed && pair?.input_hash===deliveryInputHash(submission,data)
    && pair?.base64 && pair?.audit_base64
    && artifactHash(Buffer.from(pair.base64,'base64'))===pair.sha256
    && artifactHash(Buffer.from(pair.audit_base64,'base64'))===pair.audit_sha256) {
    return {...pair,archived_at:new Date().toISOString()};
  }
  return data.previous_approved_artifact || null;
}
