import { createHash } from 'node:crypto';

// Template changes invalidate artifact approval, not source selection or saved prose.
export const RENDERER_VERSION = 7;
export const ARTIFACT_REVIEW_VERSION = 3;

function stable(value: any): any {
  if (value instanceof Date) return value.toISOString();
  if (Array.isArray(value)) return value.map(stable);
  if (value && typeof value === 'object') return Object.fromEntries(Object.keys(value).sort().map(k => [k, stable(value[k])]));
  return value;
}
/** Bind approval to all editorial inputs, excluding the approval and generated bytes themselves. */
export function deliveryInputHash(submission: any, data: any = submission.chambersData || {}) {
  const {approved_artifact, release_verdict, cloned_docx_b64, review_checkpoint, ...inputs} = data;
  return createHash('sha256').update(JSON.stringify(stable({rendererVersion:RENDERER_VERSION,artifactReviewVersion:ARTIFACT_REVIEW_VERSION,practiceArea:submission.practiceArea, targetDirectory:submission.targetDirectory, guideRegion:submission.guideRegion, currentBand:submission.currentBand, inputs}))).digest('hex');
}
export function artifactHash(buffer: Buffer) { return createHash('sha256').update(buffer).digest('hex'); }
